# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
 swift_version = '4.2'

target 'simpleMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # Pods for simpleMVVM

  target 'simpleMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'simpleMVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
